baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Grasp App'
theme = ["reveal-hugo"]

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true